logging:
  level:
    org.hibernate.SQL: "TRACE"

spring:
  application:
    name: "chatapp"

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: "update"

    open-in-view: false

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  data:
    redis:
      host: "${REDIS_HOST:localhost}"
      port: "${REDIS_PORT:6379}"
  output:
    ansi:
      enabled: "ALWAYS"

  servlet:
    multipart:
      enabled: true
      max-file-size: "100MB"
      max-request-size: "150MB"
      file-size-threshold: "2KB"

server:
  port: "${PORT:8000}"

jwts:
  public-key: "classpath:certs/jwts/public.pem"
  private-key: "classpath:certs/jwts/private.pem"

  access-token-lifetime: "PT60M" # 30 minutes
  refresh-token-lifetime: "P30D" # 30 days

  secret-key: "${JWT_SECRET}"

cloudinary:
  api-key: "${CLOUDINARY_API_KEY}"
  api-secret: "${CLOUDINARY_API_SECRET}"
  cloud-name: "${CLOUDINARY_CLOUD_NAME}"

messages:
  max-request: 30